### ISSUE TITLE
The function "image_distance_from_dataset" can not be found

### ISSUE THREAD

**Issue by YuxinCHENGPE** [ethanweber/nerfiller#12]

**Comment by ethanweber** [comment]
Hey @YuxinCHENGPE, I missed this issue until now. I'm including that file just for reference in case people are interested in DreamBooth experiments. However, I don't plan to make this code runnable or provide data for it. So probably best to use look at the code as reference instead of using it plug-and-play for any of the LORA fine-tuning experiments. Thanks for understanding! :)
