### ISSUE TITLE
llff dataset question

### ISSUE THREAD

**Issue by Arcxml** [ethanweber/nerfiller#8]
Hello, thank you very much for your project. I want to ask a question, as far as I understand, the nerfstudio library does not support LLFF type dataset, but I see that you have used the SPIN dataset. Did you perform additional processing on its data?

**Comment by ethanweber** [comment]
Hi! So [this part of the code](https://github.com/ethanweber/nerfiller/blob/9cdcb20af74fe2083d574b5ad017e697f1c86cd9/notebooks/spinnerf_to_nerfstudio.ipynb#L38), [this part of the code](https://github.com/ethanweber/nerfiller/blob/9cdcb20af74fe2083d574b5ad017e697f1c86cd9/nerfiller/experiments/data.py#L35), and [this part of the code](https://github.com/ethanweber/nerfiller/blob/9cdcb20af74fe2083d574b5ad017e697f1c86cd9/nerfiller/experiments/base.py#L126) might be relevant. We convert the format to Nerfstudio and then turn off distortion loss with `forward_facing_snippet = "--pipeline.model.distortion_loss_mult 0.0"`. It's not foolproof but it works for some scenes like the backpack we show from the SPIN dataset. However, I don't think all of their captures will work as well. We didn't use the full dataset. You might also want to play with setting the near and far distances when sampling rays. Essentially, you can try to get Nerfacto's scene contraction to work instead of supporting LLFF NDC directly.
